site:
  name: FAIR
  full_name: Fundamental AI Research Institute
  university: The University of Texas at Dallas
  year: 2025
  email: fair@utdallas.edu
nav:
  - label: Research
    url: research.html
  - label: People
    url: people.html
  - label: Centers + Partners
    url: centers.html
  - label: Opportunities
    url: opportunities.html
  - label: Partnerships
    url: partnerships.html
  - label: News
    url: news.html
